baseurl = "/"
languageCode = "en-us"
title = "Operating the Foundry"
theme = "hugo-material-docs"
metadataformat = "yaml"
# canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-67001027-2"

[params]
	# General information
	author = "sgreenberg@pivotal.io"
	description = "CF Foundation Training - Operating Cloud Foundry"
	copyright = "Copyright Cloud Foundry Foundation.  All Rights Reserved."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/cloudfoundry/summit-training-classes"

	version = "2.0.0"
  headerLogo = "/img/cf-white.png"
  logo = "img/cf-rabbit.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["css/style.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "blue"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "cloudfoundry/summit-training-classes"


[[menu.main]]
	name   = "Overview"
	url    = ""
	weight = 0

[[menu.main]]
	name   = "Prerequisites"
	url    = "prereqs/"
	weight = 10

[[menu.main]]
	name   = "Agenda"
	url    = "agenda/"
	weight = 20

[[menu.main]]
	name   = "Resources"
	url    = "resources/"
	weight = 30

[[menu.main]]
	name   = "Notes"
	url    = "notes/"
	weight = 35

[[menu.main]]
	name   = "License"
	url    = "http://www.apache.org/licenses/LICENSE-2.0"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
